#!/bin/bash
# =============================================================================
# JULES INITIAL SETUP SCRIPT (FORK STRATEGY) - Updated for x.titan v2
# Copy content of this file to: 
# Codebases -> x.titan -> Configuration -> Initial Setup
# =============================================================================
set -e

echo "🔧 Configuring environment for x.titan (Fork Strategy)..."

# 0. Save Repo Root
REPO_ROOT=$(pwd)

# 1. Install TA-Lib (System Dependency)
# -----------------------------------------------------------------------------
# Note: Jules pre-installs many tools. We use sudo for system libs.
if [ ! -f "/usr/lib/libta_lib.so" ] && [ ! -f "/usr/local/lib/libta_lib.so" ]; then
    echo "⬇️ Installing TA-Lib C Library..."
    cd /tmp
    wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz -q
    tar -xzf ta-lib-0.4.0-src.tar.gz
    cd ta-lib
    ./configure --prefix=/usr > /dev/null
    make > /dev/null
    sudo make install > /dev/null
    cd ..
    rm -rf ta-lib*
    
    # CRITICAL: Go back to repo root to find requirements.txt later
    echo "🔙 Returning to repository root: $REPO_ROOT"
    cd "$REPO_ROOT"
else
    echo "✅ TA-Lib system library found."
fi

# 1.1 Configure Python Version (Jules default is 3.12, we need 3.10)
# -----------------------------------------------------------------------------
if command -v pyenv >/dev/null; then
    echo "🐍 Setting Python to 3.10 via pyenv..."
    pyenv install 3.10.18 -s  # Install only if missing
    pyenv local 3.10.18
    pyenv rehash
else
    echo "⚠️ pyenv not found, using system python (hope it is compatible)"
fi

# 2. Configure Environment Variables
# -----------------------------------------------------------------------------
# This .env is for Jules agent testing/development.
# Production credentials should be injected via secure means.
echo "📝 Generating .env..."
cat <<'EOF' > .env
# =============================================================================
# x.titan Environment Configuration (Jules Agent)
# Generated by Jules Setup Script
# =============================================================================

# Trading
TRADING__SYMBOL=R_100
TRADING__TIMEFRAME=1m
TRADING__STAKE_AMOUNT=1.0
TRADING__PAYOUT_RATIO=0.95
TRADING__BARRIER_OFFSET=0.50
TRADING__BARRIER2_OFFSET=-0.50
TRADING__STALE_CANDLE_THRESHOLD=5.0

# Thresholds
# REAL_TRADE: >= 70% confidence
# SHADOW_TRADE: 40%-69% (learning zone)
# IGNORE: < 40%
THRESHOLDS__CONFIDENCE_THRESHOLD_HIGH=0.70
THRESHOLDS__LEARNING_THRESHOLD_MIN=0.40
THRESHOLDS__LEARNING_THRESHOLD_MAX=0.69

# Hyperparameters
HYPERPARAMS__LEARNING_RATE=0.0005
HYPERPARAMS__BATCH_SIZE=128
HYPERPARAMS__DROPOUT_RATE=0.2
HYPERPARAMS__LSTM_HIDDEN_SIZE=256
HYPERPARAMS__CNN_FILTERS=64
HYPERPARAMS__LATENT_DIM=16
HYPERPARAMS__USE_TFT=true
HYPERPARAMS__FUSION_DROPOUT=0.2
HYPERPARAMS__HEAD_DROPOUT=0.1
HYPERPARAMS__TEMPORAL_EMBED_DIM=64
HYPERPARAMS__SPATIAL_EMBED_DIM=64
HYPERPARAMS__FUSION_OUTPUT_DIM=256
HYPERPARAMS__REGIME_CAUTION_THRESHOLD=0.2
HYPERPARAMS__REGIME_VETO_THRESHOLD=0.5
HYPERPARAMS__EWC_SAMPLE_SIZE=5000
HYPERPARAMS__TFT_POOLING_METHOD=attention

# Data shapes
DATA_SHAPES__SEQUENCE_LENGTH_TICKS=1000
DATA_SHAPES__SEQUENCE_LENGTH_CANDLES=200
DATA_SHAPES__FEATURE_DIM_CANDLES=10
DATA_SHAPES__FEATURE_DIM_TICKS=1
DATA_SHAPES__FEATURE_DIM_VOLATILITY=4
DATA_SHAPES__WARMUP_STEPS=50
DATA_SHAPES__LABEL_THRESHOLD_TOUCH=0.005
DATA_SHAPES__LABEL_THRESHOLD_RANGE=0.003

# General
ENVIRONMENT=development
SEED=42
DEVICE_PREFERENCE=auto

# Deriv API Token (Dummy token for testing - replace with real token for live trading via secure secrets)
DERIV_API_TOKEN=dummy_token_for_testing
DERIV_APP_ID=1089

# Dashboard Access
DASHBOARD_API_KEY=titan-dev

# Execution Safety - Development/Testing Configuration
EXECUTION_SAFETY__MAX_TRADES_PER_MINUTE=5
EXECUTION_SAFETY__MAX_TRADES_PER_MINUTE_PER_SYMBOL=3
EXECUTION_SAFETY__MAX_DAILY_LOSS=50.0
EXECUTION_SAFETY__MAX_STAKE_PER_TRADE=10.0
EXECUTION_SAFETY__MAX_RETRY_ATTEMPTS=3
EXECUTION_SAFETY__RETRY_BASE_DELAY=1.0
EXECUTION_SAFETY__KILL_SWITCH_ENABLED=false
EXECUTION_SAFETY__CIRCUIT_BREAKER_RESET_MINUTES=15

# Calibration Monitoring
CALIBRATION__ERROR_THRESHOLD=1.0
CALIBRATION__CONSECUTIVE_THRESHOLD=5
CALIBRATION__WINDOW_SIZE=20

# Shadow Trade Configuration
CONTRACTS__DURATION_MINUTES=1
CONTRACTS__DURATION_RISE_FALL=1
CONTRACTS__DURATION_TOUCH=5
CONTRACTS__DURATION_RANGE=5
SHADOW_TRADE__MIN_PROBABILITY_TRACK=0.45
SHADOW_TRADE__STALENESS_THRESHOLD_MINUTES=5

# Heartbeat and Monitoring
HEARTBEAT__INTERVAL_SECONDS=60
HEARTBEAT__STALE_DATA_THRESHOLD_SECONDS=30

# Normalization Scaling Factors
NORMALIZATION__NORM_FACTOR_VOLATILITY=20.0
NORMALIZATION__NORM_FACTOR_ATR=100.0
NORMALIZATION__NORM_FACTOR_RSI_STD=0.02
NORMALIZATION__NORM_FACTOR_BB_WIDTH=10.0

# Observability
OBSERVABILITY__ENABLE_PROMETHEUS=true
OBSERVABILITY__HEALTH_CHECK_FILE_PATH=logs/system_health.json

# System Resource Management
SYSTEM__LOG_RETENTION_DAYS=7
SYSTEM__DB_RETENTION_DAYS=30
SYSTEM__SYSTEM_DB_PATH=data_cache/trading_state.db
EOF

# 3. Install Python Dependencies
# -----------------------------------------------------------------------------
echo "📦 Installing Python dependencies..."
pip install --upgrade pip

# Install ta-lib python wrapper (requires system lib from step 1)
pip install ta-lib

# Install project requirements
pip install -r requirements.txt

# 4. CUSTOM FORK INSTALLATION (Clean Install)
# -----------------------------------------------------------------------------
echo "🔧 Installing custom python-deriv-api from Fork..."

# Use pip to install directly from git - keeps the repo clean
# This avoids leaving a 'python-deriv-api' folder in your workspace
pip install git+https://github.com/planetazul3/python-deriv-api.git@master

echo "✅ Fork installed successfully."

# 5. Verification
# -----------------------------------------------------------------------------
echo "🔍 Running verification checks..."

# Verify critical imports
python -c "
import sys
print(f'Python version: {sys.version}')

# Core ML
import torch
print(f'✅ PyTorch: {torch.__version__}')

# Data processing
import pandas
import numpy
import talib
print(f'✅ Pandas: {pandas.__version__}')
print(f'✅ NumPy: {numpy.__version__}')
print(f'✅ TA-Lib: {talib.__version__}')

# Configuration
import pydantic
print(f'✅ Pydantic: {pydantic.__version__}')

# Custom API
import deriv_api
print(f'✅ Deriv API loaded from: {deriv_api.__file__}')

print('\\n✅ All critical dependencies verified!')
"

# 6. CLEANUP (Crucial for Jules Verification)
# -----------------------------------------------------------------------------
# Jules requires a clean working tree to finish snapshot creation.
echo "🧹 Cleaning up workspace to satisfy Jules verification..."

# Remove local python version file created by pyenv
if [ -f ".python-version" ]; then
    rm ".python-version"
fi

# Final reset to ensure no untracked files or modifications remain
# This won't affect the installed packages in the environment
git reset --hard HEAD
echo "✨ Workspace is clean. Setup complete."
